/** Viral product names + HA personality copy + route map */

export const BRAND = {
  appName: 'Magic Sanctum',
  shortName: 'Magic',
  tagline: 'Stir, breathe, receive — then decide with a wink.',
  domain: 'https://magic.hazelallure.com',
  pet: {
    id: 'familiar_whisperer',
    route: '/familiar',
    name: 'Familiar Whisperer',
    short: 'Pet talk',
    emoji: '🐾',
    tagline: 'What is your familiar *actually* plotting?',
    pro: true,
    guide: '/guides/familiar-whisperer',
  },
  coach: {
    id: 'before_the_storm',
    route: '/before-the-storm',
    name: 'Before the Storm',
    short: 'Storm prep',
    emoji: '🕯',
    tagline: 'Words for the fight you have not had yet (or the one you just survived).',
    pro: true,
    guide: '/guides/before-the-storm',
  },
  settler: {
    id: 'hearth_court',
    route: '/hearth-court',
    name: 'Hearth Court',
    short: 'Court',
    emoji: '⚖',
    tagline: 'Free: enter sides, vote, computer decides. Pro: live multi-device + full cliffs.',
    pro: false,
    guide: '/guides/hearth-court',
  },
  dice: {
    id: 'sanctum_dice',
    route: '/dice',
    name: 'Sanctum Dice',
    short: 'Dice',
    emoji: '🎲',
    tagline: 'List options. Let the dice choose. Free forever.',
    pro: false,
  },
  thisOrThat: {
    id: 'this_or_that',
    route: '/this-or-that',
    name: 'This or That',
    short: 'T/T',
    emoji: '⚡',
    tagline: 'Two options. One theatrical pick. Pass the phone.',
    pro: false,
  },
  mood: {
    id: 'mood_meter',
    route: '/mood',
    name: 'Mood Meter',
    short: 'Mood',
    emoji: '🌙',
    tagline: 'Energy · peace · connection + free moon phase.',
    pro: false,
  },
  sphere: {
    id: 'sanctum_sphere',
    route: '/',
    name: 'Sanctum Sphere',
    short: 'Sphere',
    emoji: '⑧',
    tagline: 'Ask anything. Entertainment only.',
    pro: false,
    guide: '/guides/sanctum-sphere',
  },
  coin: {
    id: 'heaven_ember',
    route: '/?mode=coin',
    name: 'Heaven & Ember Coin',
    short: 'Coin',
    emoji: '🪙',
    tagline: 'YES from the clouds. NO from the coals.',
    pro: false,
    guide: '/guides/heaven-ember-coin',
  },
  journal: {
    id: 'frustration_cauldron',
    route: '/cauldron',
    name: 'Frustration Cauldron',
    short: 'Cauldron',
    emoji: '🔥',
    tagline: 'Vent privately. Or feed the Hearth.',
    pro: false,
    guide: '/guides/frustration-cauldron',
  },
  widget: {
    id: 'desk_orb',
    route: '/widget',
    name: 'Desk Orb',
    short: 'Widget',
    emoji: '🖥',
    tagline: 'Minimal companion — pin the tab or open after install.',
    pro: false,
    guide: '/guides/desk-orb',
  },
  harmony: {
    id: 'chart_harmony',
    route: '/compatibility',
    name: 'Chart Harmony',
    short: 'Match',
    emoji: '💞',
    tagline: 'Two birthdays · playful compatibility score.',
    pro: false,
    guide: '/guides/chart-harmony',
  },
};

/** Flat actionable routes for sitemap / menus */
export const TOOL_LINKS = [
  { to: '/', label: 'Sanctum Sphere', emoji: '⑧' },
  { to: '/?mode=coin', label: 'Heaven & Ember', emoji: '🪙' },
  { to: '/dashboard', label: 'Dashboard', emoji: '⭐' },
  { to: '/compatibility', label: 'Chart Harmony', emoji: '💞' },
  { to: '/pathfinder', label: 'Pathfinder', emoji: '🗺' },
  { to: '/hearth-court', label: 'Hearth Court', emoji: '⚖' },
  { to: '/dice', label: 'Sanctum Dice', emoji: '🎲' },
  { to: '/this-or-that', label: 'This or That', emoji: '⚡' },
  { to: '/mood', label: 'Mood Meter', emoji: '🌙' },
  { to: '/familiar', label: 'Familiar Whisperer', emoji: '🐾' },
  { to: '/before-the-storm', label: 'Before the Storm', emoji: '🕯' },
  { to: '/cauldron', label: 'Frustration Cauldron', emoji: '🔥' },
  { to: '/widget', label: 'Desk Orb Widget', emoji: '🖥' },
  { to: '/free', label: 'Free Playground', emoji: '🎁' },
  { to: '/oracle/daily', label: 'Daily Oracle', emoji: '🌙' },
  { to: '/guides', label: 'Guides', emoji: '📖' },
  { to: '/settings', label: 'Settings', emoji: '⚙' },
  { to: '/legal', label: 'Policies', emoji: '📜' },
  { to: '/auth', label: 'Sign in', emoji: '🔑' },
];

export const DISCLAIMER =
  'Entertainment only — not medical, legal, financial, therapeutic, or professional advice. If you are unsafe, contact local emergency services.';

export const WHIMSY_LOADING = [
  'Warming the hearth…',
  'Consulting the moon…',
  'Stirring the cauldron…',
  'Asking the familiar…',
  'Aligning the Sanctum…',
  'Polishing the sphere…',
  'Counting cliff notes…',
];

/** Map guide slug → try-it route */
export const GUIDE_TRY_ROUTES = {
  'sanctum-sphere': '/',
  'heaven-ember-coin': '/?mode=coin',
  'hearth-court': '/hearth-court',
  'familiar-whisperer': '/familiar',
  'before-the-storm': '/before-the-storm',
  'frustration-cauldron': '/cauldron',
  'magic-sanctum-for-seekers': '/free',
  'desk-orb': '/widget',
  'chart-harmony': '/compatibility',
  'daily-fortune': '/dashboard',
};
