/**
 * Marketing + product catalog for Maker Studio tools.
 * Free vs Pro comparison and signup use this as source of truth.
 */

export const MAKER_STUDIO_TOOLS = [
  {
    id: 'harvest_calendar',
    name: 'Batch / harvest calendar',
    free: 'View & 3 dates',
    pro: 'Unlimited restock calendar + public “coming soon”',
    proOnly: false,
    blurb: 'Tell shoppers when lavender, salves, or tea blends return so they wait instead of leaving.',
  },
  {
    id: 'wholesale',
    name: 'Wholesale / min-order mode',
    free: '—',
    pro: '✓ min qty, wholesale price, B2B note',
    proOnly: true,
    blurb: 'Serve boutiques, spas, and yoga studios with bulk pricing without a second website.',
  },
  {
    id: 'blend_requests',
    name: 'Custom blend request form',
    free: '—',
    pro: '✓ deposits, timeline, inbox',
    proOnly: true,
    blurb: 'Oil and tea custom blends with intent notes and optional deposit workflow.',
  },
  {
    id: 'label_pdf',
    name: 'Label / ingredient card PDF',
    free: 'Preview text',
    pro: '✓ download print-ready card',
    proOnly: false,
    blurb: 'Structure/function ingredient cards for jars — fewer labeling headaches.',
  },
  {
    id: 'allergen_pet',
    name: 'Allergen & pet-safety badges',
    free: 'Basic allergen tags',
    pro: '✓ pet caution + badge pack on listings',
    proOnly: false,
    blurb: 'Clear trust signals for essential oils, nuts, and pet-sensitive homes.',
  },
  {
    id: 'pickup_slots',
    name: 'Local pickup window slots',
    free: 'Simple hours',
    pro: '✓ capacity slots (e.g. 10–12 / 2–4)',
    proOnly: false,
    blurb: 'Cap how many pickups you take per window on market or porch days.',
  },
  {
    id: 'consignment',
    name: 'Consignment tracker',
    free: '—',
    pro: '✓ stock at studios/markets + sell-through',
    proOnly: true,
    blurb: 'Track jars left at a studio or market booth and what sold.',
  },
  {
    id: 'ritual_tags',
    name: 'Shop-by-ritual / concern tags',
    free: '3 tags',
    pro: 'Unlimited ritual tags on your catalog',
    proOnly: false,
    blurb: 'Sleep, cleanse, moon, focus — your shelf, not only sitewide filters.',
  },
  {
    id: 'gift_wrap',
    name: 'Gift note + wrap upsell',
    free: '—',
    pro: '✓ checkout gift options',
    proOnly: true,
    blurb: 'High AOV for apothecary gifts — note + wrap at checkout.',
  },
  {
    id: 'sub_box',
    name: 'Monthly apothecary box',
    free: '—',
    pro: '✓ mystery/staple refill plan copy + link',
    proOnly: true,
    blurb: 'Position a recurring “shelf refill” box for loyal seekers.',
  },
  {
    id: 'cross_kits',
    name: 'Cross-shop kits (same vendor)',
    free: '—',
    pro: '✓ kit builder (oil + candle + tea)',
    proOnly: true,
    blurb: 'Raise average order with ready-made ritual kits from your own SKUs.',
  },
  {
    id: 'intent_quiz',
    name: 'Seeker intent quiz → match',
    free: 'Link to site quiz',
    pro: '✓ your branded soft-match quiz',
    proOnly: false,
    blurb: 'Non-medical “what are you seeking?” flow that lands on your products.',
  },
  {
    id: 'claim_helper',
    name: 'Claim language helper',
    free: '✓ rewrite suggestions',
    pro: '✓ save compliant library',
    proOnly: false,
    blurb: 'Turn “cures insomnia” into structure/function language before you publish.',
  },
  {
    id: 'state_rules',
    name: 'State cottage / herbal rules checklist',
    free: 'Top 5 states',
    pro: '✓ full US checklist + notes',
    proOnly: false,
    blurb: 'Educational shipping-state reminders — not legal advice.',
  },
  {
    id: 'photo_score',
    name: 'Photo quality score',
    free: '✓ checklist',
    pro: '✓ score history on listings',
    proOnly: false,
    blurb: 'Lighting, label readable, white space — before go-live.',
  },
  {
    id: 'maker_story',
    name: 'Verified maker story',
    free: 'Short bio',
    pro: '✓ origin, lineage, sourcing blocks',
    proOnly: false,
    blurb: 'Where herbs come from, woman-owned note, lineage — trust that converts.',
  },
  {
    id: 'voice_listing',
    name: 'Voice-to-listing draft',
    free: '—',
    pro: '✓ paste transcript → listing draft',
    proOnly: true,
    blurb: 'Talk your product; get a structured draft with tags and care notes.',
  },
  {
    id: 'supplier_alerts',
    name: 'Supplier reorder alerts',
    free: '—',
    pro: '✓ weekly email-yourself low-stock plan',
    proOnly: true,
    blurb: 'Remind yourself to reorder carrier oils, jars, and herbs.',
  },
  {
    id: 'packing_list',
    name: 'Market packing list',
    free: 'Print basic list',
    pro: '✓ qty by SKU + booth checklist',
    proOnly: false,
    blurb: 'Print what to pack for market day by product and quantity.',
  },
  {
    id: 'auto_reply',
    name: 'Quiet hours / auto-reply templates',
    free: '1 template',
    pro: '✓ sabbatical + quiet-hour replies',
    proOnly: false,
    blurb: 'DM/email scripts when you’re at market or on rest.',
  },
  {
    id: 'storefront_sections',
    name: 'Custom storefront sections',
    free: 'About only',
    pro: '✓ lineage / sourcing / care cards',
    proOnly: true,
    blurb: 'Unique page blocks so your shop doesn’t look like a template.',
  },
  {
    id: 'seasonal_skins',
    name: 'Seasonal theme skins',
    free: '—',
    pro: '✓ Samhain, Yule, spring, etc.',
    proOnly: true,
    blurb: 'Seasonal storefront mood without hiring a designer.',
  },
  {
    id: 'client_vault',
    name: 'Private client vault',
    free: '—',
    pro: '✓ past blends/orders notes for VIPs',
    proOnly: true,
    blurb: 'Remember repeat clients’ preferred blends and notes.',
  },
  {
    id: 'office_hours',
    name: 'Office hours booking',
    free: 'Link to sessions',
    pro: '✓ paid consult office hours',
    proOnly: false,
    blurb: 'Offer limited paid consult slots without full calendar chaos.',
  },
];

export const MAKER_STUDIO_FREE_SIGNUP = [
  'Claim language helper for compliant product copy',
  'Photo quality checklist before you publish',
  'Harvest calendar (limited) & packing list for markets',
  'Pickup hours + basic allergen tags',
  'Maker story basics & quiet-hour reply template',
  'Core listings (limits) + POS stock counts',
];

export const MAKER_STUDIO_PRO_SIGNUP = [
  'Wholesale / min-order for spas & boutiques',
  'Custom blend request inbox + deposits',
  'Gift wrap & note upsells at checkout',
  'Cross-shop kits & monthly box positioning',
  'Consignment tracker for studio/market stock',
  'Voice-to-listing drafts & supplier reorder alerts',
  'Seasonal skins, custom storefront sections, client vault',
  'Full harvest calendar, capacity pickup slots, print labels',
  'Subscribe & Save, tax pack, market-day mode, review QR',
  'Campaigns, Teaching Sanctum, unlimited listings & team seats',
];

export function freeVsProRowsFromCatalog() {
  return MAKER_STUDIO_TOOLS.map((t) => [t.name, t.free, t.pro]);
}
