/** Linked feature cards for active Pro subscribers — member & practitioner hubs */

export const PRO_MEMBER_BENEFIT_CARDS = [
  {
    id: 'discounts',
    icon: '✨',
    titleKey: 'pro.hub.member.discounts.title',
    descKey: 'pro.hub.member.discounts.desc',
    ctaKey: 'pro.hub.open',
    to: '/services',
    tier: 'signature',
  },
  {
    id: 'courses',
    icon: '📜',
    titleKey: 'pro.hub.member.courses.title',
    descKey: 'pro.hub.member.courses.desc',
    ctaKey: 'pro.hub.open',
    to: '/courses',
    tier: 'signature',
  },
  {
    id: 'favorites',
    icon: '♥',
    titleKey: 'pro.hub.member.favorites.title',
    descKey: 'pro.hub.member.favorites.desc',
    ctaKey: 'pro.hub.open',
    to: '/favorites',
    tier: 'essential',
  },
  {
    id: 'loyalty',
    icon: '🌟',
    titleKey: 'pro.hub.member.loyalty.title',
    descKey: 'pro.hub.member.loyalty.desc',
    ctaKey: 'pro.hub.open',
    to: '/customer-portal',
    tier: 'essential',
  },
  {
    id: 'ratings',
    icon: '☆',
    titleKey: 'pro.hub.member.ratings.title',
    descKey: 'pro.hub.member.ratings.desc',
    ctaKey: 'pro.hub.open',
    to: '/customer-portal',
    tier: 'essential',
  },
  {
    id: 'express',
    icon: '⚡',
    titleKey: 'pro.hub.member.express.title',
    descKey: 'pro.hub.member.express.desc',
    ctaKey: 'pro.hub.open',
    to: '/products',
    tier: 'premier',
  },
  {
    id: 'profile',
    icon: '🖼',
    titleKey: 'pro.hub.member.profile.title',
    descKey: 'pro.hub.member.profile.desc',
    ctaKey: 'pro.hub.customize',
    to: '/account-settings#profile-studio',
    tier: 'premier',
  },
  {
    id: 'gathering',
    icon: '🔥',
    titleKey: 'pro.hub.member.gathering.title',
    descKey: 'pro.hub.member.gathering.desc',
    ctaKey: 'pro.hub.open',
    to: '/gathering',
    tier: 'premier',
  },
  {
    id: 'sanctum',
    icon: '🏛',
    titleKey: 'pro.hub.member.sanctum.title',
    descKey: 'pro.hub.member.sanctum.desc',
    ctaKey: 'pro.hub.open',
    to: '/sanctum-student-hub',
    tier: 'premier',
  },
  {
    id: 'tarot',
    icon: '🃏',
    titleKey: 'pro.hub.member.tarot.title',
    descKey: 'pro.hub.member.tarot.desc',
    ctaKey: 'pro.hub.open',
    to: '/tarot-collection',
    tier: 'signature',
  },
  {
    id: 'remedies',
    icon: '🌿',
    titleKey: 'pro.hub.member.remedies.title',
    descKey: 'pro.hub.member.remedies.desc',
    ctaKey: 'pro.hub.open',
    to: '/remedies',
    tier: 'signature',
  },
  {
    id: 'support',
    icon: '🛟',
    titleKey: 'pro.hub.member.support.title',
    descKey: 'pro.hub.member.support.desc',
    ctaKey: 'pro.hub.open',
    to: '/support',
    tier: 'essential',
  },
];

export const PRO_VENDOR_BENEFIT_CARDS = [
  {
    id: 'listings',
    icon: '📋',
    titleKey: 'pro.hub.vendor.listings.title',
    descKey: 'pro.hub.vendor.listings.desc',
    ctaKey: 'pro.hub.open',
    to: '/vendor-dashboard',
    tier: 'signature',
  },
  {
    id: 'teaching',
    icon: '📚',
    titleKey: 'pro.hub.vendor.teaching.title',
    descKey: 'pro.hub.vendor.teaching.desc',
    ctaKey: 'pro.hub.open',
    to: '/vendor-teaching',
    tier: 'signature',
  },
  {
    id: 'storefront',
    icon: '🏪',
    titleKey: 'pro.hub.vendor.storefront.title',
    descKey: 'pro.hub.vendor.storefront.desc',
    ctaKey: 'pro.hub.customize',
    to: '/storefront-settings',
    tier: 'premier',
  },
  {
    id: 'campaigns',
    icon: '✉',
    titleKey: 'pro.hub.vendor.campaigns.title',
    descKey: 'pro.hub.vendor.campaigns.desc',
    ctaKey: 'pro.hub.open',
    to: '/vendor-campaigns',
    tier: 'premier',
  },
  {
    id: 'analytics',
    icon: '📊',
    titleKey: 'pro.hub.vendor.analytics.title',
    descKey: 'pro.hub.vendor.analytics.desc',
    ctaKey: 'pro.hub.open',
    to: '/vendor-dashboard',
    tier: 'essential',
  },
  {
    id: 'discounts',
    icon: '💫',
    titleKey: 'pro.hub.vendor.discounts.title',
    descKey: 'pro.hub.vendor.discounts.desc',
    ctaKey: 'pro.hub.open',
    to: '/vendor-dashboard',
    tier: 'essential',
  },
  {
    id: 'international',
    icon: '🌍',
    titleKey: 'pro.hub.vendor.international.title',
    descKey: 'pro.hub.vendor.international.desc',
    ctaKey: 'pro.hub.open',
    to: '/storefront-settings',
    tier: 'premier',
  },
  {
    id: 'lounge',
    icon: '🕯',
    titleKey: 'pro.hub.vendor.lounge.title',
    descKey: 'pro.hub.vendor.lounge.desc',
    ctaKey: 'pro.hub.open',
    to: '/vendor-gathering',
    tier: 'signature',
  },
  {
    id: 'credentials',
    icon: '🎓',
    titleKey: 'pro.hub.vendor.credentials.title',
    descKey: 'pro.hub.vendor.credentials.desc',
    ctaKey: 'pro.hub.open',
    to: '/vendor-teaching',
    tier: 'premier',
  },
];

export const TIER_STYLES = {
  essential: {
    badgeKey: 'pro.hub.tier.essential',
    ring: 'ring-[#4a1942]/15',
    border: 'border-[#4a1942]/12',
    iconBg: 'bg-[#4a1942]/8',
  },
  premier: {
    badgeKey: 'pro.hub.tier.premier',
    ring: 'ring-[#c9a227]/25',
    border: 'border-[#c9a227]/30',
    iconBg: 'bg-gradient-to-br from-[#c9a227]/20 to-[#e8dcc8]/40',
  },
  signature: {
    badgeKey: 'pro.hub.tier.signature',
    ring: 'ring-[#b76e79]/25',
    border: 'border-[#b76e79]/25',
    iconBg: 'bg-gradient-to-br from-[#b76e79]/15 to-[#f4e8ec]',
  },
};